---
title: "Cophylo analysis-IQ-TREE2"
output: html_document
date: "2024-12-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ape)
library(phytools)
library(phangorn)
library(ggtree)
library(ggplot2)
library(grid)
library(markdown)
library(RColorBrewer)
library(fuzzyjoin)
library(stringr)

knitr::opts_knit$set(root.dir = "~/benchmark_demulticoder")
seed <- 1
set.seed(seed)
```

### Read in data
```{r, read in data}
cox1 <- ape::read.tree("rps10_cox1_phylogeny/data/cox1_mafft2_aligned_auto_ugenetrim.fasta.treefile")
cox1 <- midpoint(cox1)
rps10 <- read.tree("rps10_cox1_phylogeny/data/rps10_mafft2_aligned_auto_ugenetrim.fasta.treefile")
rps10 <- midpoint(rps10)

datasettable <- read.table("rps10_cox1_phylogeny/data/phyloinfo_cox1rps10.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE, quote = "")
assoctable <- read.table("rps10_cox1_phylogeny/data/assoc_table.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE, quote = "")
```

### Check that tips match
```{r, check that tips match}
all(cox1$tip.label %in% rps10$tip.label)

cox1_tips <- cox1$tip.label
rps10_tips <- rps10$tip.label

cox1_not_in_rps10 <- setdiff(cox1_tips, rps10_tips)
rps10_not_in_cox1 <- setdiff(rps10_tips, cox1_tips)

cat("Tip labels in cox1 but not in rps10:\n")
print(cox1_not_in_rps10)
cat("\nTip labels in rps10 but not in cox1:\n")
print(rps10_not_in_cox1)

all.equal(sort(cox1$tip.label), sort(rps10$tip.label))
```


### Make cophylogeny
```{r, make cophylogeny}
# Define genus colors
genus_colors <- setNames(c("darkturquoise", "#3399FF", "#FF4500", "#7851A9"), unique(datasettable$genus))

# Function to color the tips based on the dataset
color_tips <- function(tree, dataset, genus_colors) {
  tip_colors <- genus_colors[dataset$genus[match(tree$tip.label, dataset$strain)]]
  return(tip_colors)
}

# Make association table
cox1_tip_colors <- color_tips(cox1, datasettable, genus_colors)
rps10_tip_colors <- color_tips(rps10, datasettable, genus_colors)

# Debugging: Print out the mappings to check for correctness
print("cox1 tip labels and colors:")
print(data.frame(tip.label = cox1$tip.label, color = cox1_tip_colors))

print("rps10 tip labels and colors:")
print(data.frame(tip.label = rps10$tip.label, color = rps10_tip_colors))

# Check if any NA values are present in the tip colors
if (any(is.na(cox1_tip_colors))) {
  warning("NA values found in cox1_tip_colors")
}
if (any(is.na(rps10_tip_colors))) {
  warning("NA values found in rps10_tip_colors")
}

# Create cophylo object
obj <- phytools::cophylo(multi2di(cox1), multi2di(rps10), assoc = assoctable, rotate.multi = TRUE)

# Set up branch support colors for the first tree
t1edgecount <- length(obj$trees[[1]]$edge[,2])
t1edgelist <- seq(1, t1edgecount)
t1support <- as.data.frame(list(text = as.character(obj$trees[[1]]$node.label[2:obj$trees[[1]]$Nnode]), edge = sapply(2:obj$trees[[1]]$Nnode + Ntip(obj$trees[[1]]), function(n, e) which(e == n), e = obj$trees[[1]]$edge[,2])), stringsAsFactors = FALSE)
t1support <- merge(data.frame(seqcount = t1edgelist), t1support, by.x = "seqcount", by.y = "edge", all.x = TRUE)
t1support$text[t1support$text == ""] <- "100/100"
t1support$text[is.na(t1support$text)] <- "100/100"
t1support$shalrt <- as.numeric(sub("/.*", "", t1support$text))
t1support$ufboot <- as.numeric(sub(".*/", "", t1support$text))
t1support$color <- ifelse(t1support$shalrt >= 80 & t1support$ufboot >= 95, "black", "gray")

# Set up branch support colors for the second tree
t2edgecount <- length(obj$trees[[2]]$edge[,2])
t2edgelist <- seq(1, t2edgecount)
t2support <- as.data.frame(list(text = as.character(obj$trees[[2]]$node.label[2:obj$trees[[2]]$Nnode]), edge = sapply(2:obj$trees[[2]]$Nnode + Ntip(obj$trees[[2]]), function(n, e) which(e == n), e = obj$trees[[2]]$edge[,2])), stringsAsFactors = FALSE)
t2support <- merge(data.frame(seqcount = t2edgelist), t2support, by.x = "seqcount", by.y = "edge", all.x = TRUE)
t2support$text[t2support$text == ""] <- "100/100"
t2support$text[is.na(t2support$text)] <- "100/100"
t2support$shalrt <- as.numeric(sub("/.*", "", t2support$text))
t2support$ufboot <- as.numeric(sub(".*/", "", t2support$text))
t2support$color <- ifelse(t2support$shalrt >= 80 & t2support$ufboot >= 95, "black", "gray")

edge.col <- list(
  left = t1support$color,
  right = t2support$color
)

# Color links by genus
link_colors <- genus_colors[datasettable$genus[match(assoctable$cox1, assoctable$rps10)]]

color_nodes <- function(tree, edge_colors) {
  node_colors <- rep("black", Ntip(tree) + tree$Nnode)
  for (i in seq_along(edge_colors)) {
    node_colors[tree$edge[i, 2]] <- edge_colors[i]
  }
  return(node_colors)
}

# Color nodes for both trees
cox1_node_colors <- color_nodes(obj$trees[[1]], t1support$color)
rps10_node_colors <- color_nodes(obj$trees[[2]], t2support$color)

# Plot the cophylogeny
pdf("rps10_cox1_phylogeny/figures/figure_cox_vs_rps10_unique_auto_rotatemultitrue_midpoint_coloredges.pdf", width = 8.5, height = 11, useDingbats = FALSE)
plot(obj, tip.len = 0.01, fsize = 0.20, scale.bar = c(0.2, 0.2), pts = FALSE, link.lwd = 1, link.col = link_colors, edge.col = edge.col)

# Add tip labels with colors
tiplabels.cophylo(pch = 21, bg = "black", cex = 0.4, which = "left")
tiplabels.cophylo(pch = 21, bg = "black", cex = 0.4, which = "right")

dev.off()
```

```{r session info}
sessioninfo::session_info()
```