---
title: "Cophylo analysis"
output: html_document
date: "2024-12-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ape)
#library(phyloch)
library(phytools)
library(phangorn)
library(ggtree)
library(ggplot2)
library(grid)
library(markdown)
library(RColorBrewer)
library(fuzzyjoin)
library(stringr)

knitr::opts_knit$set(root.dir = "~/benchmark_demulticoder")
seed <- 1
set.seed(seed)
```

### Read in the data
```{r, read in trees}
cox1<-ape::read.tree("rps10_cox1_phylogeny/cox1_db_mafft_auto.fasta.treefile")
cox1<-midpoint(cox1)
rps10<-read.tree("rps10_cox1_phylogeny/rps10_db_mafft_auto_ugene.fasta.treefile")
datasettable <- read.table("rps10_cox1_phylogeny/phyloinfo_cox1rps10.txt", sep = "\t", header=T, stringsAsFactors = F, quote = "")
```


###Tip names should already match, but let's check
```{r, check tip names}
all(cox1$tip.label %in% rps10$tip.label)
```

###Let's do cophylo analysis
```{r, cophylo}
obj<-phytools::cophylo(multi2di(cox1),multi2di(rps10), rotate.multi=FALSE)
obj


pdf("Figure_cox_vs_rps10.pdf",width=8.5,height=11,useDingbats=FALSE)
plot(obj,tip.len=0.01,fsize=0.2,scale.bar=c(0.2,0.2),pts=FALSE)
title(main=paste0("cox1_vs_rps10"), line=-1)
	
	#set tip labels for left tree
	#tiplabels.cophylo(pch=21, bg=p1,cex=1)
	#set tip labels for right tree
	#tiplabels.cophylo(pch=i2, which="right",bg=p2,col=p2bor,cex=1)
dev.off()
```


```{r, make cophylogeny}
obj <- phytools::cophylo(multi2di(cox1), multi2di(rps10), rotate.multi = TRUE)

genus_colors <- setNames(rainbow(length(unique(datasettable$genus))), unique(datasettable$genus))

color_tips <- function(tree, dataset, genus_colors) {
  tip_colors <- genus_colors[dataset$genus[match(tree$tip.label, dataset$tip_label)]]
  return(tip_colors)
}

cox1_tip_colors <- color_tips(cox1, datasettable, genus_colors)
rps10_tip_colors <- color_tips(rps10, datasettable, genus_colors)

pdf("Figure_cox_vs_rps10.pdf", width = 8.5, height = 11, useDingbats = FALSE)
plot(obj, tip.len = 0.01, fsize = 0.2, scale.bar = c(0.2, 0.2), pts = FALSE)
title(main = "cox1_vs_rps10", line = -1)

tiplabels.cophylo(pch = 21, bg = cox1_tip_colors, cex = 1, which = "left")

tiplabels.cophylo(pch = 21, bg = rps10_tip_colors, cex = 1, which = "right")

dev.off()
```